Now sign in/up fails if the user enters a wrong code more than 3 times.

diff --git a/linux_build b/linux_build
--- a/linux_build
+++ b/linux_build
@@ -1,7 +1,12 @@
 #!/bin/bash
+# Can only be run in a safe deploy environment
+if [ `\git status | \egrep -i 'nothing to commit, working tree clean' | \wc -l` = 0 ] ; then
+  echo "ERROR: You cannot build for linux with checked out changes."
+  exit 1
+fi
+
 for i in `find . -name '*.go' -print` ; do
   perl -i -ne 'print if (!/production:remove/i);' "$i"
 done
 
-GOOS=linux GOARCH=amd64 go build main.go
-\mv main fiber-basic-auth
+GOOS=linux GOARCH=amd64 go build -o fiber-basic-auth
