Oops: Actual final steps towards safe, working `prod_deploy`.

diff --git a/prod_deploy b/prod_deploy
--- a/prod_deploy
+++ b/prod_deploy
@@ -1,3 +1,12 @@
 #!/bin/bash -e -x
+# Can only be run in a safe deploy environment
+if [ `\git status | \egrep -i 'nothing to commit, working tree clean' | \wc -l` = 0 ] ; then
+  echo "ERROR: You cannot build for linux with checked out changes."
+  exit 1
+fi
+
 ./linux_build && \
   echo 'Insert your deploy command(s) here.'
+
+# Go back to
+git reset --hard HEAD
